version: '3.8'
services:
  db:
    image: postgres:15
    container_name: my-portpolio_db
    restart: always
    environment:
      POSTGRES_USER: dongt
      POSTGRES_PASSWORD: dongt
      POSTGRES_DB: my-portpolio
    ports:
      - '5432:5432'
    volumes:
      - portpolio_data:/var/lib/postgresql/data

volumes:
  portpolio_data:
    driver: local
