import './global.css';
import { Sidebar } from '@/blog-admin-ui';

export const metadata = {
  title: 'Welcome to blog_admin',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <section className="grid grid-cols-[auto_1fr]">
          <Sidebar />
          {children}
        </section>
      </body>
    </html>
  );
}
