import './global.css';
import { BlogHeader } from '@/blog-ui';

export const metadata = {
  title: 'Welcome to blog',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="grid grid-rows-[74px,1fr] h-screen bg-gray-300">
        <BlogHeader />
        <section className="w-full max-w-[1366px] mx-auto bg-white">
          {children}
        </section>
      </body>
    </html>
  );
}
