import './global.css';

export const metadata = {
  title: 'Welcome to blog',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <section className='max-w-[1366px] mx-auto'>
          {children}
        </section>
      </body>
    </html>
  );
}
