name: CI - Test and Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  cicd-check:
    if: github.event_name == 'push' || github.event.action == 'opened' || github.event.action == 'synchronize'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run tests
        run: npx nx affected -t test --passWithNoTests=true --no-cloud

      - name: Run lint
        run: npx nx run @my-portpolio/source:lint --fix --no-cloud
